### PR TITLE
New form select that runs in SDA 3.x

### PR DESCRIPTION
**Pull request by tecneider**
[BTI-760 GS Jira -  "No issue type selected" error in SDA Version 3.8.3 (175)](https://platformsolutions.atlassian.net/browse/BTI-760)

The functionality of the multiselect is lost in this PR. (For a multiselect the user will get a single select, they will have to go to JIRA to select more than one value) I will raise a story for the multi-select version.

Once this PR is merged and a new version of the is pushed to artifactory I will update jira with the necessary changes.

This PR
- Removed react-select and replaced it with downshift
- Fixed rollup build (introduced by downshift)
- The component should look and act like the old one - no change in the interface.
- bumped the eis-common-ui version ready for a new release

### CODE REVIEW

**Comment by selena-mallet** [comment]
click on the arrow button has no effect

**Comment by selena-mallet** [comment]
bug in the scroll container over top (minor)

[select_scroll.zip](https://github.com/SymphonyOSF/eis-common-ui/files/4146893/select_scroll.zip)

**Comment by tecneider** [comment]
Fixed both caret click behaviour 
Fixed the outer container scroll behaviour

**Comment by selena-mallet** [comment]
close with the arrow in an empty drop-down fails

[close-empty-dropdown.zip](https://github.com/SymphonyOSF/eis-common-ui/files/4148775/close-empty-dropdown.zip)

**Comment by tecneider** [comment]
Fixed second click of caret not closing input

**Pull request merged**
